### ISSUE TITLE
The logic of drawer's folder seems a little bit odd

### ISSUE THREAD

**Issue by Deleted-Account** [yang991178/fluent-reader#64] opened 2020-08-08 05:17 UTC
Click on the folder's title, I expect to open/close the folder,
but it closes/expands the upper folder.
emm, kinda werid...

Another issue is it seems not so compatible with portrait monitor.
Regardless I maximize this app on a portrait 4K screen with 200% UI scale,
it could only show the drawer or the contents of a feed/folder.
Hope the width of drawer could be flexible.
As well hope it could show drawer and feed's contents simultaneously and have a better experience with portrait screen.

Thanks for your great work again~

**Comment by yang991178** [comment] 2020-08-08 06:00
I don't quite understand what you mean by "to open/close the folder". The first click should reveal the articles of the group and the second click onward should toggle the sources in the group. 

If your screen is too narrow, showing the menu will result in no space for the article in list view. I don't know if there is a good way to accommodate that.

**Comment by Deleted-Account** [comment] 2020-08-08 07:54
I'm now using v0.7.1 Beta

Assuming all the folders I have are:
Folder A
Folder B
Folder C
If I click on Folder C's title or arrow, it's gonna expand/close Folder B but not Folder C **in drawer**.
( I didn't say "in drawer" before. Sorry to confuse you. )
And I didn't figure out how to close Folder C in drawer... : (

---

![Fluent](https://user-images.githubusercontent.com/48331538/89703974-919a3600-d982-11ea-8f81-2d12cb71f069.png)
And with the portrait view.
I found that the minimum pixel which could show drawer and contents simultaneous is 1141 with 4 columns.
Article's width is 860 pixels no matter what width the app is. (While showing article, the drawer is hidden behind blur effect.)
Minimum width of this app is 992 pixels ( or 990? )

4K monitor in portrait view with 200% UI scale is regarded as 1080p wide for many apps.
1080p is just 61 pixels less than 1141.

I assume that 1080p is not too narrow, and showing 3 columns feeds' contents with drawer on 1080p screen is kinda suitable enough.
And maybe even with minimum width 992 pixels, showing drawer with 2 columns as well seems acceptable.

Thanks for your reply.
I'd appreciate it if you could consider to make a switch option that could show drawer and contents persistently.
Or to make the minimum gap between feeds' contents from 25 pixels to 10 ( then it could show drawer and 4 columns contents on 1080p )
Or to make the minimum columns of contents ( which still showing drawer ) from 4 to 3 ( or even 2? ).

**Comment by yang991178** [comment] 2020-08-08 07:59
Regarding the folder issue, go to "groups" in settings and delete all empty groups if there is any and see if the issue is solved. Thanks for reporting this bug.

**Comment by Deleted-Account** [comment] 2020-08-08 08:03
> Regarding the folder issue, go to "groups" in settings and delete all empty groups if there is any and see if the issue is solved. Thanks for reporting this bug.

It works!
After I deleted two empty groups, clicking on drawer labels works properly  : )

**Comment by yang991178** [comment] 2020-08-14 01:22
This bug is resolved in 0.7.2. Unfortunately I won't work on pinning the menu for narrower screen sizes as `1080 - 280 - 350 = 450 px` isn't enough for articles in list view.

**Closed by yang991178** 2020-08-14 01:22 UTC
Labels: bug, in progress
