### ISSUE TITLE
Is this repo still alive?

### ISSUE THREAD

**Issue by Shituation** [yang991178/fluent-reader#459] opened 2022-08-29 15:48 UTC
**Describe the bug**
No response from dev since 2021.

**To Reproduce**
1. Go to Issues
2. Click on 'new issue'
3. Scroll down to 'submit new issue'
4. Wait forever for an answer

**Expected behavior**
To get a response from the dev.

**Platform (please complete the following information):**
 - OS: Windows 10

**Comment by yang991178** [comment] 2022-08-30 00:27
Closing this since I can't reproduce the issue.

**Closed by yang991178** 2022-08-30 00:27 UTC
