### ISSUE TITLE
Article titles incorrectly parsed

### ISSUE THREAD

**Issue by alexwent** [yang991178/fluent-reader#494] opened 2022-12-09 23:57 UTC
For one source (aldaily.com/feed) the titles of articles still contain unresolved markup such as <strong></strong> and <em></em> Please see attached screenshot for multiple examples.

**Additional context**

I'm using Windows 11 64-bit 22H2, althugh this is not relevant to the problem. I had the same problem with the yarr self-hosted RSS reader, and the developer was able to solve the problem. I hope that you will also be able to help. Many thanks in advance

![image](https://user-images.githubusercontent.com/89491663/206813701-14a5ab29-b32d-4e03-a820-f909641088c4.png)

**Comment by yang991178** [comment] 2022-12-21 23:24
(Duplicate of #67)

**Closed by yang991178** 2022-12-21 23:24 UTC
