### ISSUE TITLE
"Simple" Ad blocking for web viewer

### ISSUE THREAD

**Issue by bakinazik** [yang991178/fluent-reader#281] opened 2021-07-09 12:30 UTC
**Is your feature request related to a problem? Please describe.**
If the feed links are to be opened with the browser viewer, there should be ad blocker support.

**Describe the solution you'd like**
As I wrote above, adblock support should come.

**Comment by yang991178** [comment] 2021-07-10 19:26
You can always use PAC scripts for simple AD blocking or use a global blocker for better effects. This is a duplicate of #18 (not in english).

**Closed by yang991178** 2021-07-10 19:26 UTC

**Comment by xmha97** [comment] 2025-08-16 12:31
+1
