### ISSUE TITLE
Inconsistent UX priorities given to user actions

### ISSUE THREAD

**Issue by dylankenneally** [yang991178/fluent-reader#470] opened 2022-09-17 07:43 UTC
**Describe the bug**
The order of user actions on the toolbar found at the bottom of an article being viewed and on the right-click context menu does not match.

**To Reproduce**
1. Use "List view"
2. Click on an article in the list
3. Right click on the same list item
4. Note difference in order

**Expected behavior**
The order should be the same, with the actions the user is most likely wanting to take at the top of the context menu/left of the toolbar. Suggested order:
- Open externally 
- Add Star/Remove Star
- Mark as [read | unread]
- [Hide | Unhide]
- Copy link

Also suggest the removal of:
- Read: does nothing the user cant to by clicking the article
- Share: unless its going to be linked in with the platform share services
- Copy title: the user has a means of doing this elsewhere, feels redundant
- Load webpage: redundant, user has a browser they can use for this 

Other glitches spotted while writing this:
- "Star" tells the user nothing, should be "Add to favourites"
- "Star" vs. "Remove star" isn't consistent, both should be in the form of "[verb] [context]" 

**Screenshots**
<img width="938" alt="image" src="https://user-images.githubusercontent.com/12589363/190846248-419424a4-3b05-468f-a8e1-5a3c082fd03b.png">

**Platform (please complete the following information):**
 - OS: OS: macOS Monterey (v12.5.1)
 - Version v1.1.2

**Additional context**
n/a

**Comment by yang991178** [comment] 2022-09-18 06:38
This is the intended behavior. Closing this as it is more of personal opinions than actual bug report / feature request. Sorry about that.

**Closed by yang991178** 2022-09-18 06:38 UTC
